using System;
using System.Collections.Generic;
using UnityEngine;
using UnityEngine.Serialization;

namespace OptimizedFeature.Scripts
{
    [Serializable]
    public class VATClipInfo
    {
        public string ClipName;
        [SerializeField] private int _stateHash;

        public int StateHash
        {
            get
            {
                if (_stateHash == 0 && !string.IsNullOrEmpty(ClipName))
                {
                    _stateHash = GenerateHash(ClipName);
                }
                return _stateHash;
            }
            set => _stateHash = value;
        }

        public int StartFrame;
        public int EndFrame;
        public float FrameRate = 30f;
        public bool IsLooping = true;

        public static int GenerateHash(string str)
        {
            if (string.IsNullOrEmpty(str)) return 0;
            unchecked
            {
                uint hash = 2166136261;
                for (int i = 0; i < str.Length; i++)
                {
                    hash = (hash ^ str[i]) * 16777619;
                }
                return (int)hash;
            }
        }
    }

    [Serializable]
    public class VATWeaponAssetEntry
    {
#if UNITY_EDITOR
        // This is strictly authoring metadata: it labels the generated asset and
        // the Editor-created sub-render GameObject. Player lookup never uses it.
        [InspectorName("Item Name")]
        public string WeaponName = "Item";
#endif
        [SerializeField] private int _weaponHash = DefaultItemHash;
        [InspectorName("Item Asset")]
        public VATWeaponAssetSO WeaponAsset;

        public static readonly int DefaultItemHash = VATClipInfo.GenerateHash("Item");

        // Kept as the legacy serialized/runtime identifier for compatibility
        // with existing VAT assets and external callers.
        public static readonly int DefaultWeaponHash = VATClipInfo.GenerateHash("Weapon");

        /// <summary>
        /// Stable runtime identifier used to equip a VAT item channel.
        /// The property name remains WeaponHash for serialized/API compatibility.
        /// Zero is reserved for legacy/default-item fallback.
        /// </summary>
        public int WeaponHash
        {
            get => _weaponHash;
            set => _weaponHash = value;
        }

#if UNITY_EDITOR
        public void EnsureWeaponHash()
        {
            if (_weaponHash != 0)
            {
                return;
            }

            string legacyName = string.IsNullOrWhiteSpace(WeaponName) ? "Item" : WeaponName.Trim();
            _weaponHash = VATClipInfo.GenerateHash(legacyName);
        }
#endif
    }

    /// <summary>
    /// ScriptableObject generated by VATBakeTool holding Body VAT animation data
    /// and optional Item VAT assets that share its clip frame manifest. The
    /// serialized Weapon* field/type names are retained for backward compatibility.
    /// </summary>
    [CreateAssetMenu(fileName = "VATAssetData", menuName = "VAT/VAT Asset Data")]
    public class VATAssetDataSO : ScriptableObject
    {
        public Texture2D VATTexture;
        public Mesh BakedStaticMesh;
        public Vector3 BoundingMin;
        public Vector3 BoundingMax;
        public int TotalVertices;
        public int TotalFrames;

        // Cumulative local scale from the first common parent that contains the
        // baked SkinnedMeshRenderers through every ancestor up to the
        // hierarchy root. VAT vertices/textures are stored normalized in the
        // common parent's local space; Runtime Setup restores this cumulative
        // scale on the generated model root.
        public Vector3 ModelScale = Vector3.one;

        public List<VATClipInfo> Clips = new List<VATClipInfo>();
        public List<Material> BakedMaterials = new List<Material>();

        // Optional VAT payloads for item/sub-render channels. Every item
        // shares the body clip frame manifest, while retaining independent
        // meshes, vertex counts, bounds, materials and position textures.
        [InspectorName("Item Assets")]
        public List<VATWeaponAssetEntry> WeaponAssets = new List<VATWeaponAssetEntry>();

        // Legacy/default entry retained for existing scenes and the single
        // item flow. New bakes assign it to the first hashed item asset.
        [InspectorName("Default Item Asset")]
        public VATWeaponAssetSO DefaultWeaponAsset;

        [Header("VAT Animator")]
        /// <summary>
        /// Default baked clip used when no independent VATAssetAnimatorSO is
        /// linked. The value is the VATClipInfo.StateHash of the clip.
        /// </summary>
        [FormerlySerializedAs("_legacyDefaultStateName")]
        public int DefaultStateName;

        /// <summary>
        /// Independent animator payload for this VAT data. Clips remain owned by
        /// this asset; parameters, transitions, blend trees and graph data are
        /// owned by the referenced VATAssetAnimatorSO.
        /// </summary>
        public VATAssetAnimatorSO AnimatorAsset;

        // Kept only to migrate existing VATAssetDataSO files when their animator
        // asset is created from the graph tool. New bakes keep the default clip
        // directly on this asset so AnimatorAsset remains optional.
        [SerializeField, HideInInspector, FormerlySerializedAs("AnimatorParameters")]
        private List<VATAnimatorParameterData> _legacyAnimatorParameters = new List<VATAnimatorParameterData>();
        [SerializeField, HideInInspector, FormerlySerializedAs("AnimatorTransitions")]
        private List<VATAnimatorTransitionData> _legacyAnimatorTransitions = new List<VATAnimatorTransitionData>();
        [SerializeField, HideInInspector, FormerlySerializedAs("AnimatorBlendTrees")]
        private List<VATAnimatorBlendTreeData> _legacyAnimatorBlendTrees = new List<VATAnimatorBlendTreeData>();

        /// <summary>
        /// Resolves the state used by the runtime on startup. An explicitly
        /// linked AnimatorAsset owns the default in graph-driven mode;
        /// otherwise the baked default stored on this asset is used.
        /// </summary>
        public int EffectiveDefaultStateName =>
            AnimatorAsset != null ? AnimatorAsset.DefaultStateName : DefaultStateName;

        /// <summary>
        /// Updates the default owned by the active animator representation.
        /// The graph uses this instead of writing directly to DefaultStateName
        /// so linked AnimatorAsset data remains authoritative.
        /// </summary>
        public void SetAnimatorDefaultStateName(int stateHash)
        {
            if (AnimatorAsset != null)
            {
                AnimatorAsset.DefaultStateName = stateHash;
            }
            else
            {
                DefaultStateName = stateHash;
            }
        }

        public List<VATAnimatorParameterData> AnimatorParameters
        {
            get => AnimatorAsset != null ? AnimatorAsset.AnimatorParameters : _legacyAnimatorParameters;
            set
            {
                if (AnimatorAsset != null) AnimatorAsset.AnimatorParameters = value;
                else _legacyAnimatorParameters = value;
            }
        }

        public List<VATAnimatorTransitionData> AnimatorTransitions
        {
            get => AnimatorAsset != null ? AnimatorAsset.AnimatorTransitions : _legacyAnimatorTransitions;
            set
            {
                if (AnimatorAsset != null) AnimatorAsset.AnimatorTransitions = value;
                else _legacyAnimatorTransitions = value;
            }
        }

        public List<VATAnimatorBlendTreeData> AnimatorBlendTrees
        {
            get => AnimatorAsset != null ? AnimatorAsset.AnimatorBlendTrees : _legacyAnimatorBlendTrees;
            set
            {
                if (AnimatorAsset != null) AnimatorAsset.AnimatorBlendTrees = value;
                else _legacyAnimatorBlendTrees = value;
            }
        }

#if UNITY_EDITOR
        [SerializeField, HideInInspector, FormerlySerializedAs("AnimatorGraph")]
        private VATAnimatorGraphData _legacyAnimatorGraph = new VATAnimatorGraphData();

        public VATAnimatorGraphData AnimatorGraph
        {
            get => AnimatorAsset != null ? AnimatorAsset.AnimatorGraph : _legacyAnimatorGraph;
            set
            {
                if (AnimatorAsset != null) AnimatorAsset.AnimatorGraph = value;
                else _legacyAnimatorGraph = value;
            }
        }
#endif

        private Dictionary<int, VATClipInfo> _clipHashCache;
        private Dictionary<int, VATWeaponAssetSO> _weaponHashCache;

        private void OnEnable()
        {
            _clipHashCache = null;
            _weaponHashCache = null;
            EnsureLegacyAnimatorLists();
        }

        private void OnValidate()
        {
            if (Clips != null)
            {
                for (int i = 0; i < Clips.Count; i++)
                {
                    if (Clips[i] != null)
                    {
                        Clips[i].StateHash = VATClipInfo.GenerateHash(Clips[i].ClipName);
                    }
                }
            }
#if UNITY_EDITOR
            if (WeaponAssets != null)
            {
                for (int i = 0; i < WeaponAssets.Count; i++)
                {
                    if (WeaponAssets[i] != null)
                    {
                        WeaponAssets[i].EnsureWeaponHash();
                    }
                }
            }
#endif
            _clipHashCache = null;
            _weaponHashCache = null;
            EnsureLegacyAnimatorLists();
        }

        private void EnsureLegacyAnimatorLists()
        {
            if (_legacyAnimatorParameters == null) _legacyAnimatorParameters = new List<VATAnimatorParameterData>();
            if (_legacyAnimatorTransitions == null) _legacyAnimatorTransitions = new List<VATAnimatorTransitionData>();
            if (_legacyAnimatorBlendTrees == null) _legacyAnimatorBlendTrees = new List<VATAnimatorBlendTreeData>();
            if (WeaponAssets == null) WeaponAssets = new List<VATWeaponAssetEntry>();
#if UNITY_EDITOR
            if (_legacyAnimatorGraph == null) _legacyAnimatorGraph = new VATAnimatorGraphData();
            if (_legacyAnimatorGraph.nodes == null) _legacyAnimatorGraph.nodes = new List<VATAnimatorNodeData>();
            if (_legacyAnimatorGraph.edges == null) _legacyAnimatorGraph.edges = new List<VATAnimatorEdgeData>();
#endif
        }

#if UNITY_EDITOR
        public bool HasLegacyAnimatorData()
        {
            EnsureLegacyAnimatorLists();
            return DefaultStateName != 0 ||
                   _legacyAnimatorParameters.Count > 0 ||
                   _legacyAnimatorTransitions.Count > 0 ||
                   _legacyAnimatorBlendTrees.Count > 0 ||
                   (_legacyAnimatorGraph != null &&
                    ((_legacyAnimatorGraph.nodes != null && _legacyAnimatorGraph.nodes.Count > 0) ||
                     (_legacyAnimatorGraph.edges != null && _legacyAnimatorGraph.edges.Count > 0)));
        }

        public void MigrateLegacyAnimatorDataTo(VATAssetAnimatorSO animatorAsset)
        {
            if (animatorAsset == null) return;

            EnsureLegacyAnimatorLists();
            animatorAsset.CopyFromLegacy(
                DefaultStateName,
                _legacyAnimatorParameters,
                _legacyAnimatorTransitions,
                _legacyAnimatorBlendTrees,
                _legacyAnimatorGraph);
            _legacyAnimatorParameters.Clear();
            _legacyAnimatorTransitions.Clear();
            _legacyAnimatorBlendTrees.Clear();
            _legacyAnimatorGraph = new VATAnimatorGraphData();
        }
#endif

        private void InitializeClipCache()
        {
            if (_clipHashCache != null && _clipHashCache.Count == Clips.Count) return;

            _clipHashCache = new Dictionary<int, VATClipInfo>(Clips.Count);
            for (int i = 0; i < Clips.Count; i++)
            {
                VATClipInfo clip = Clips[i];
                if (clip != null)
                {
                    _clipHashCache[clip.StateHash] = clip;
                }
            }
        }

        public VATClipInfo GetClip(string clipName)
        {
            int hash = VATClipInfo.GenerateHash(clipName);
            return GetClip(hash);
        }

        public VATClipInfo GetClip(int stateHash)
        {
            InitializeClipCache();
            if (_clipHashCache.TryGetValue(stateHash, out var clip))
            {
                return clip;
            }
            return null;
        }

        private void InitializeWeaponCache()
        {
            int weaponCount = WeaponAssets == null ? 0 : WeaponAssets.Count;
            if (_weaponHashCache != null)
            {
                return;
            }

            _weaponHashCache = new Dictionary<int, VATWeaponAssetSO>(weaponCount);
            for (int i = 0; i < weaponCount; i++)
            {
                VATWeaponAssetEntry entry = WeaponAssets[i];
                if (entry != null && entry.WeaponAsset != null &&
                    entry.WeaponHash != 0 && !_weaponHashCache.ContainsKey(entry.WeaponHash))
                {
                    _weaponHashCache.Add(entry.WeaponHash, entry.WeaponAsset);
                }
            }
        }

        /// <summary>
        /// Resolves a weapon payload exclusively by its runtime WeaponHash.
        /// </summary>
        public VATWeaponAssetSO GetWeaponAsset(int weaponHash)
        {
            InitializeWeaponCache();
            if (weaponHash != 0 && _weaponHashCache != null &&
                _weaponHashCache.TryGetValue(weaponHash, out VATWeaponAssetSO weaponAsset))
            {
                return weaponAsset;
            }

            // Preserve existing prefabs/assets that do not yet contain a hash.
            return weaponHash == 0 ? DefaultWeaponAsset : null;
        }

#if UNITY_EDITOR
        /// <summary>
        /// Editor-only re-bake lookup. Runtime weapon selection must use GetWeaponAsset(int).
        /// </summary>
        public VATWeaponAssetSO GetWeaponAssetByEditorName(string weaponName)
        {
            if (!string.IsNullOrEmpty(weaponName) && WeaponAssets != null)
            {
                for (int i = 0; i < WeaponAssets.Count; i++)
                {
                    VATWeaponAssetEntry entry = WeaponAssets[i];
                    if (entry != null && entry.WeaponAsset != null &&
                        string.Equals(entry.WeaponName, weaponName, StringComparison.OrdinalIgnoreCase))
                    {
                        return entry.WeaponAsset;
                    }
                }
            }

            return WeaponAssets == null || WeaponAssets.Count <= 1
                ? DefaultWeaponAsset
                : null;
        }
#endif
    }
}
