using System;
using System.Collections.Generic;
using UnityEngine;

namespace OptimizedFeature.Scripts
{
    [Serializable]
    public class VATClipInfo
    {
        public string ClipName;
        [SerializeField] private int _stateHash;

        public int StateHash
        {
            get
            {
                if (_stateHash == 0 && !string.IsNullOrEmpty(ClipName))
                {
                    _stateHash = GenerateHash(ClipName);
                }
                return _stateHash;
            }
            set => _stateHash = value;
        }

        public int StartFrame;
        public int EndFrame;
        public float FrameRate = 30f;
        public bool IsLooping = true;

        public static int GenerateHash(string str)
        {
            if (string.IsNullOrEmpty(str)) return 0;
            unchecked
            {
                uint hash = 2166136261;
                for (int i = 0; i < str.Length; i++)
                {
                    hash = (hash ^ str[i]) * 16777619;
                }
                return (int)hash;
            }
        }
    }

    [Serializable]
    public class VATSocketTransformData
    {
        public string SocketName;
        public Vector3[] LocalPositions;
        public Quaternion[] LocalRotations;
    }

    [Serializable]
    public class VATWeaponAssetEntry
    {
        public string WeaponName = "Weapon";
        public VATWeaponAssetSO WeaponAsset;
    }

    /// <summary>
    /// ScriptableObject generated by VATBakeTool holding Body VAT animation data
    /// and an optional Weapon VAT asset that shares its clip frame manifest.
    /// </summary>
    [CreateAssetMenu(fileName = "VATAssetData", menuName = "VAT/VAT Asset Data")]
    public class VATAssetDataSO : ScriptableObject
    {
        public Texture2D VATTexture;
        public Mesh BakedStaticMesh;
        public Vector3 BoundingMin;
        public Vector3 BoundingMax;
        public int TotalVertices;
        public int TotalFrames;

        public List<VATClipInfo> Clips = new List<VATClipInfo>();
        public List<VATSocketTransformData> Sockets = new List<VATSocketTransformData>();
        public List<Material> BakedMaterials = new List<Material>();

        // Optional VAT payloads for weapon/sub-render channels. Every weapon
        // shares the body clip frame manifest, while retaining independent
        // meshes, vertex counts, bounds, materials and position textures.
        public List<VATWeaponAssetEntry> WeaponAssets = new List<VATWeaponAssetEntry>();

        // Legacy/default entry retained for existing scenes and the single
        // weapon flow. New bakes assign it to the first named weapon asset.
        public VATWeaponAssetSO DefaultWeaponAsset;

        [Header("VAT Animator Runtime Data")]
        /// <summary>
        /// State hash of the clip connected to the editor-only Default node.
        /// The field name is retained as part of the VAT animator data contract.
        /// </summary>
        public int DefaultStateName;
        public List<VATAnimatorParameterData> AnimatorParameters = new List<VATAnimatorParameterData>();
        public List<VATAnimatorTransitionData> AnimatorTransitions = new List<VATAnimatorTransitionData>();
        public List<VATAnimatorBlendTreeData> AnimatorBlendTrees = new List<VATAnimatorBlendTreeData>();

#if UNITY_EDITOR
        [Header("VAT Animator Editor Graph")]
        public VATAnimatorGraphData AnimatorGraph = new VATAnimatorGraphData();
#endif

        private Dictionary<int, VATClipInfo> _clipHashCache;

        private void OnEnable()
        {
            _clipHashCache = null;
            EnsureAnimatorLists();
        }

        private void OnValidate()
        {
            if (Clips != null)
            {
                for (int i = 0; i < Clips.Count; i++)
                {
                    if (Clips[i] != null)
                    {
                        Clips[i].StateHash = VATClipInfo.GenerateHash(Clips[i].ClipName);
                    }
                }
            }
            _clipHashCache = null;
            EnsureAnimatorLists();
        }

        private void EnsureAnimatorLists()
        {
            if (AnimatorParameters == null) AnimatorParameters = new List<VATAnimatorParameterData>();
            if (AnimatorTransitions == null) AnimatorTransitions = new List<VATAnimatorTransitionData>();
            if (AnimatorBlendTrees == null) AnimatorBlendTrees = new List<VATAnimatorBlendTreeData>();
            if (WeaponAssets == null) WeaponAssets = new List<VATWeaponAssetEntry>();
#if UNITY_EDITOR
            if (AnimatorGraph == null) AnimatorGraph = new VATAnimatorGraphData();
            if (AnimatorGraph.nodes == null) AnimatorGraph.nodes = new List<VATAnimatorNodeData>();
            if (AnimatorGraph.edges == null) AnimatorGraph.edges = new List<VATAnimatorEdgeData>();
#endif
        }

        private void InitializeClipCache()
        {
            if (_clipHashCache != null && _clipHashCache.Count == Clips.Count) return;

            _clipHashCache = new Dictionary<int, VATClipInfo>(Clips.Count);
            for (int i = 0; i < Clips.Count; i++)
            {
                VATClipInfo clip = Clips[i];
                if (clip != null)
                {
                    _clipHashCache[clip.StateHash] = clip;
                }
            }
        }

        public VATClipInfo GetClip(string clipName)
        {
            int hash = VATClipInfo.GenerateHash(clipName);
            return GetClip(hash);
        }

        public VATClipInfo GetClip(int stateHash)
        {
            InitializeClipCache();
            if (_clipHashCache.TryGetValue(stateHash, out var clip))
            {
                return clip;
            }
            return null;
        }

        public VATSocketTransformData GetSocket(string socketName)
        {
            for (int i = 0; i < Sockets.Count; i++)
            {
                if (Sockets[i].SocketName == socketName)
                {
                    return Sockets[i];
                }
            }
            return null;
        }

        public VATWeaponAssetSO GetWeaponAsset(string weaponName)
        {
            if (!string.IsNullOrEmpty(weaponName) && WeaponAssets != null)
            {
                for (int i = 0; i < WeaponAssets.Count; i++)
                {
                    VATWeaponAssetEntry entry = WeaponAssets[i];
                    if (entry != null && entry.WeaponAsset != null &&
                        string.Equals(entry.WeaponName, weaponName, StringComparison.OrdinalIgnoreCase))
                    {
                        return entry.WeaponAsset;
                    }
                }
            }

            // Legacy assets (and assets with only one weapon channel) retain
            // the original default-channel behaviour.
            return WeaponAssets == null || WeaponAssets.Count <= 1
                ? DefaultWeaponAsset
                : null;
        }
    }
}
