using System;
using System.Collections.Generic;
using UnityEngine;

namespace OptimizedFeature.Scripts
{
    [Serializable]
    public class VATClipInfo
    {
        public string ClipName;
        [SerializeField] private int _stateHash;

        public int StateHash
        {
            get
            {
                if (_stateHash == 0 && !string.IsNullOrEmpty(ClipName))
                {
                    _stateHash = GenerateHash(ClipName);
                }
                return _stateHash;
            }
            set => _stateHash = value;
        }

        public int StartFrame;
        public int EndFrame;
        public float FrameRate = 30f;
        public bool IsLooping = true;

        public static int GenerateHash(string str)
        {
            if (string.IsNullOrEmpty(str)) return 0;
            unchecked
            {
                uint hash = 2166136261;
                for (int i = 0; i < str.Length; i++)
                {
                    hash = (hash ^ str[i]) * 16777619;
                }
                return (int)hash;
            }
        }
    }

    [Serializable]
    public class VATSocketTransformData
    {
        public string SocketName;
        public Vector3[] LocalPositions;
        public Quaternion[] LocalRotations;
    }

    /// <summary>
    /// ScriptableObject generated by VATBakeTool holding animation metadata and equipment socket transforms.
    /// </summary>
    [CreateAssetMenu(fileName = "VATAssetData", menuName = "VAT/VAT Asset Data")]
    public class VATAssetDataSO : ScriptableObject
    {
        public Texture2D VATTexture;
        public Mesh BakedStaticMesh;
        public Vector3 BoundingMin;
        public Vector3 BoundingMax;
        public int TotalVertices;
        public int TotalFrames;

        public List<VATClipInfo> Clips = new List<VATClipInfo>();
        public List<VATSocketTransformData> Sockets = new List<VATSocketTransformData>();
        public List<Material> BakedMaterials = new List<Material>();

        private Dictionary<int, VATClipInfo> _clipHashCache;

        private void OnEnable()
        {
            _clipHashCache = null;
        }

        private void OnValidate()
        {
            if (Clips != null)
            {
                for (int i = 0; i < Clips.Count; i++)
                {
                    if (Clips[i] != null)
                    {
                        Clips[i].StateHash = VATClipInfo.GenerateHash(Clips[i].ClipName);
                    }
                }
            }
            _clipHashCache = null;
        }

        private void InitializeClipCache()
        {
            if (_clipHashCache != null && _clipHashCache.Count == Clips.Count) return;

            _clipHashCache = new Dictionary<int, VATClipInfo>(Clips.Count);
            for (int i = 0; i < Clips.Count; i++)
            {
                VATClipInfo clip = Clips[i];
                if (clip != null)
                {
                    _clipHashCache[clip.StateHash] = clip;
                }
            }
        }

        public VATClipInfo GetClip(string clipName)
        {
            int hash = VATClipInfo.GenerateHash(clipName);
            return GetClip(hash);
        }

        public VATClipInfo GetClip(int stateHash)
        {
            InitializeClipCache();
            if (_clipHashCache.TryGetValue(stateHash, out var clip))
            {
                return clip;
            }
            return null;
        }

        public VATSocketTransformData GetSocket(string socketName)
        {
            for (int i = 0; i < Sockets.Count; i++)
            {
                if (Sockets[i].SocketName == socketName)
                {
                    return Sockets[i];
                }
            }
            return null;
        }
    }
}
